name: CI/CD Pipeline for Python Application

on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python linter
        run: pip install pycodestyle
      - name: Run Python linter
        run: pycodestyle exercise_1

  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: install
        run: pip install build

      - name: Build Python application
        run: python3 -m build
        
      - name: Build Package
        run: cd exercise_1 &&  pip install dist/exercise_1-*.whl
     
  test:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        test_name: [test_fast, test_slow_1, test_slow_2]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:  
          python-version: 3.x

      - name: Install Python application
        run: pip install dist/exercise_1-*.whl

      - name: Run Python tests
        run: python3 tests/$test_name.py

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - name: Execute deploy script
        run: ./deploy.sh
